name: Sync Rules to Public

on:
  schedule:
    - cron: '30 23 * * *' # 北京时间 07:30
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  sync_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_RULES_TOKEN }}

      - name: 1. Pull Private Meta to Rules Folder
        uses: actions/checkout@v4
        with:
          repository: Ray2023m/Rules  
          token: ${{ secrets.SYNC_RULES_TOKEN }}
          path: Rules  
          sparse-checkout: |
            Meta
          sparse-checkout-cone-mode: false

      - name: 2. Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          rm -rf Rules/.git
          git rm -r --cached Rules/ || true
          # 仅同步 Rules 文件夹
          git add Rules/
          
          if git diff --cached --exit-code --quiet; then
            echo "No changes detected."
          else
            git commit -m "Sync: Update rules $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
